== 2015-04-02 Thursday 23:16:18
=== 自动给文件的某个pattern前加上某段文本
在cnzz.com上注册了个帐号，想统计一下这个博客的访问流量。需要给每个html文件加上一段代码，肯定不能手动呀，首先想到用 _sed_ ：

[source, bash]
$ sed -i '/regexpattern/ i text' index.html

然后希望写到makefile中，每次生成完html文件后就执行这条sed命令。但是不知道怎么在makefile里跨行执行shell代码。于是退而求其次，写到了一个外部脚本里，然后在makefile的all规则中加上这个脚本的名字。还有如果要插入的文本是在另一个文件中，需要：

[source, bash]
$ sed -i '/regexpattern/ r text.txt' index.html

=== 命令行自动登录校园网
最开始尝试了用 _curl -F_ 做表单提交，但是没有成功。网上搜到了说用 Firefox 的 Firebug 和 Firecurl 插件，可以得到每一步对应的curl命令。然后到 Firecurl 的下载页面又说：_don't use this -- use Chrome Developer Tools' "Copy as cURL", which is much more complete_

可是最终这种方法的到的curl命令也不能成功登录。

继续Google，找到了github上有人三年前写的https://github.com/tianyang-li/TUNET[Python脚本]，挺简单的，没有用表单提交，直接跟cgi交互。

于是写了个 shell 版的。。
[source, bash]
#!/bin/bash
case "$1" in
	login)
		username=${2:wdd13}
		password=$(echo -n $3 | md5sum | cut -d' ' -f1)
		curl -d "username=${username}&password=${password}&drop=0&type=1&n=100" http://net.tsinghua.edu.cn/cgi-bin/do_login
		;;
	logout)
		curl http://net.tsinghua.edu.cn/cgi-bin/do_logout
		;;
	*)
		curl -d 'action=check_online' http://net.tsinghua.edu.cn/cgi-bin/do_login                                  
		;;
esac
