Kindle Paperwhite

* 推送
	** 每个设备有一个对应的推送邮箱地址，国行一般是 '@kindle.cn', 可以在 http://z.cn/myk[这里]设置。
	** 将电子书以附件形式发送到推送邮箱地址，在Kindle设备上就会收到更新。但自己可以控制允许那些邮箱帐号可以给自己推送，如果没有被加入信任列表，那么其发送的电子书是不会被更新到Kindle中的。目前最多可以添加20个邮箱帐号。

* Calibre
	** 在电脑上下载的电子书都存入 '/media/Data/book/' 中，然后在 Calibre 的 **连接/共享** 中选择 **连接到文件夹**，就可以在多出的 **设备** 选项卡中看到所有的电子书了。将需要阅读的电子书添加到书库。
	** **Calibre书库中的电子书推送到Kindle**。设置邮箱地址：**首选项=>通过邮件分享**，需要设置：
--------------------------------------------------
	1. 发信人地址(xxx@mails.tsinghua.edu.cn)
	2. 主机名(mails.tsinghua.edu.cn)
	3. 端口(非加密:25，ssl:465)
	4. 密码
--------------------------------------------------
	之后就可以在书库中右键选中要推送的电子书，发送到Kindle了。
	** 电子书字数统计。
		*** 在**首选项=>插件=>获取新的插件** 中，搜索 'Count Pages' 插件并安装。
		*** 在**首选项=>添加栏目** 中，添加两个条目pages和words，类型都设为整数。
		*** 选择电子书，运行 'Count Pages' 插件。

* Kindle 连接 Archlinux
	** [through-line]#目前插上Kindle后，Kindle显示"USB 驱动模式"，是看不了书的。#电脑上只有在 'lsusb' 中看到有
--------------------------------------------------
Bus 004 Device 022: ID 1949:0004 Lab126, Inc. Amazon Kindle 3/4/Paperwhite
--------------------------------------------------
	** 开始以为是内核太新，但是一看发现用的是 'linux-lts' 。
	** 'go-mtfs' 和 'mtp-detect' 均未能检测出设备。
	** 安装了 'gvfs-mtp' ，重启。然后还是不行，后来准备在 'GNOME' 中看，结果 gdm 启动不了，于是开搞 'xmonad' 。快忘记Kindle的事情时，发现可以识别了。。

* Kindle 中 **位置** 的概念
	** 中文书中，一个位置大约相当于50个汉字。如果位置是 2n k，那么该书大约就有n万个汉字。
