:source-highlighter: pygments
:pygments-style: manni
== 一加手机2只能算是个半成品

自从小米丢了之后，用了两个月的Lumia 920，已经对手机失去了兴趣。但实在是受不了
2G的网络，还有WP系统，于是一加2出来之后，毫不犹豫地买了。虽然很难抢，但还
是买了，问别人要的邀请码。毕竟4G内存+64G的存储只要2399，相比小米Note顶配版真的
感觉性价比好高。

然而事实证明我真是too young, too simple. 到手之后，并没有发现有什么亮点。是真
心没有。但由于我对外形什么的要求也不高，后盖材料有点奇怪也就算了。不能换主题是
怎么回事！必须要花一百块买个后盖才能使用相应的主题，真是把我惊呆了，而且一加貌
似还把后盖作为一个卖点。感觉是有多脑残才会觉得用户有必要专门去花一百块买个后盖
？我记得买小米2S的时候，是九十块就买了个大电池加后盖。然而我确实在论坛上看到有
人把五种后盖全都买了，还满心欢喜。我表示理解不能。就像我无法理解LOL人民币玩家
为啥要花两百块买套皮肤一样。

比一加上市早的手机都普遍支持微信运动记录了，它竟然不支持。

还有应用程序快捷方式的问题，我使用QQ邮箱日历，就是装了QQ邮箱后，把里面的日历创
建为快捷方式到桌面。结果一加竟然不支持，而且连错误信息都没有，创建完了到桌面一
看什么都没有。我曾经以为这是Android的一个特色功能，在小米上第一次发现时兴奋了
好久。

图标也很乱，有方形有圆形，看起来很不舒服。第三方软件的图标是有的清楚有的模糊，
，形状更是千奇百怪，不知道怎么搞的。

还有相机，没有明显感觉出来快在哪里，照相质量一般而已，但是看图片的时候竟然要有
延时，就是在相机里打开之前拍摄的图片，点击放大的时候，需要调用图库，能明显感觉
到延迟，很影响体验。

这种破玩意儿是怎么感拿出来卖的。连个电量百分比和实时网速都没有。

我已经用了一个星期多，应该也退不了了，就是忍不住想发发牢骚。其实要是它别吹那么
大，也就算了，非要说自己不将就，是16年度旗舰。

根据我的使用体验，想想刘作虎发布会上展示的一切，都感觉是一加在打自己的脸。最好
的安卓手机之一，唉。人跟人的差距真是大。

还有他们的客服也很烂，在线客服竟然要调用QQ。我选择用微信，但是要排好长时间的队
，感觉就像只有一个人在提供客服。而且回答特别不及时，还有就是根本解决不了我的问
题。每次都是说已经有人在改进了。

可能这个氢OS由于刚刚出来，问题多也正常。但为什么要拿出来卖，还说得那么好。感觉
就像是把一加1的体验那过来说一遍，让大家觉得一加2肯定会更好，结果却是这个样子！

其实我一开始也是很积极在他们的论坛上反馈的，但是基本上没有人理睬，反复顶帖才有
人回应，而且都是水军，不能解决任何问题。让我觉得是不是大家都用得很好，没出现什
么问题。他们客服告诉我说工程师有在看论坛里的反馈，我心说有就怪了，如果看的话不
会连个回复都没有吧。记得我的小米丢之前最后一次更新的时候有个功能就是专门提交
Bug的，整个一个闭环，虽然我在两年的使用过程中几乎没遇到什么不方便的地方。

从此路人转黑。

一加跟小米差远了。少在那儿装发烧装小众装逼格了，刘作虎在发布会上说别人家手机（
应该是小米？）的发布会都是说完配置就完了，他不理解那样有什么意思。但他的一加手
机也就是配置高点啊，使用体验在哪里呢？我之前没用过4G内存的手机，现在用了没感觉
多流畅啊，有时候也卡，内存占用率也老高，总是发热呢，问题是我从来不装什么游戏软
件的。

还有一点感触就是别人的使用体验千万不能当真，“他人的美食,自己的毒药”。买手机真是
要靠运气，买了一加2，我认栽，以后有了钱，试试苹果好了。安卓实在太乱，无感了。

不是来黑一加，五毛小米的。因为我手机丢了之后是买了一加而不是小米Note。

我买手机，不是为了拿来学习怎么刷机。

:docinfo:
